### ISSUE TITLE
guam 서비스 wafflestudio-cluster 로 완전히 이관

### ISSUE THREAD

**Issue by davin111** [wafflestudio/waffle-world#10]

**Comment by davin111** [comment]
@YeonghyeonKO 내일까지 모든 guam infra 를 옮긴다구요? Kafka 어케 할 건지 안 정해지기도 하고 양이 적지 않은 거 같은데 가능할까요

**Comment by YeonghyeonKO** [comment]
Kafka 쪽은 얘기 안해봤어요. 그리고 지금 Kafka 사용하는 부분은 애초에 죽어있어서 제가 염두에 안둔듯 ㅠ
