### ISSUE TITLE
Update ArgoCD version to 2.8+

### ISSUE THREAD

**Issue by Jhvictor4** [wafflestudio/waffle-world#129]
ArgoCD UI 상에서, 정의된 CronJob 템플릿을 바탕으로 Job을 제출하도록 지원하는 기능이 2.8+ 이상 버전에 릴리즈 되었다고 합니다.
https://github.com/argoproj/argo-cd/issues/4116

해당 기능을 사용하고 싶은데 혹시 업뎃 가능할까요?

**Comment by davin111** [comment]
좋은 업데이트 공유 감사합니다.

2주쯤 전에 ArgoCD helm chart 를 [당시 최신인 5.39.0 으로 업데이트](https://github.com/wafflestudio/waffle-world/blob/main/charts/argocd/Chart.yaml#L6)했었습니다.

현재 보니까 5.42.0 이 최신인데요. [아직 ArgoCD 2.7.9 에 해당](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/Chart.yaml#L2-L6)합니다. 나중에 2.8 이상 지원되면 버전 다시 최신화 해보도록 할게요.

일단 지혁은 waffle-k8s-admin 에 속해있기도 하고, snutt 멤버들은 snutt-dev, snutt-prod 에 kubectl 권한이 있어서 `kubectl create job {job_name} --from cronjob/{cronjob_name} -n {namespace}`로도 원하는 바를 할 수 있으실 거 같은데, 특별히 요청 주신 이유가 있으실까요? 물론 저도 ArgoCD 에서 할 수 있으면 더 편할 거 같다고 생각하긴 합니다. ㅋㅋ

**Comment by davin111** [comment]
#146 작업으로 완료!
